package com.maliar.pro.database

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

@Database(
    entities = [Contact::class, Income::class, Expense::class, Check::class, Installment::class, Reminder::class, 
               Asset::class, Debt::class, FinancialGoal::class, FixedIncome::class, FinancialPreferences::class,
               ReminderEntity::class, Debtor::class, DebtorPayment::class,
               Car::class, CarOdometerLog::class, CarServiceItem::class, CarServiceLog::class,
               MealPlan::class, MealPlanEntry::class],
    version = 11,
    exportSchema = false
)
abstract class AppDatabase : RoomDatabase() {
    
    abstract fun contactDao(): ContactDao
    abstract fun accountingDao(): AccountingDao
    abstract fun reminderDao(): ReminderDao
    abstract fun financialStatusDao(): FinancialStatusDao
    abstract fun reminderEntityDao(): ReminderEntityDao
    abstract fun debtorDao(): DebtorDao
    abstract fun carDao(): CarDao
    abstract fun mealPlanDao(): MealPlanDao
    
    companion object {
        private val MIGRATION_5_6 = object : Migration(5, 6) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE advanced_reminders ADD COLUMN soundUri TEXT NOT NULL DEFAULT 'DEFAULT_ALARM'")
            }
        }
        private val MIGRATION_6_7 = object : Migration(6, 7) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE advanced_reminders ADD COLUMN repeatIntervalDays INTEGER NOT NULL DEFAULT 0")
            }
        }
        private val MIGRATION_7_8 = object : Migration(7, 8) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE advanced_reminders ADD COLUMN linkedDebtId INTEGER")
                database.execSQL("ALTER TABLE advanced_reminders ADD COLUMN linkedDebtorId INTEGER")
                database.execSQL("ALTER TABLE advanced_reminders ADD COLUMN isAutoGenerated INTEGER NOT NULL DEFAULT 0")
            }
        }
        /** Adds the whole "خودرو" module (four new, independent tables - nothing existing
         *  is touched) plus the one new nullable column on advanced_reminders that lets its
         *  service-due reminders participate in the same duplicate-avoidance pattern as
         *  checks/installments/debts/debtors. All-additive, so existing data is untouched. */
        private val MIGRATION_8_9 = object : Migration(8, 9) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE advanced_reminders ADD COLUMN linkedCarServiceId INTEGER")
                database.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `cars` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `name` TEXT NOT NULL,
                        `brand` TEXT NOT NULL DEFAULT '',
                        `model` TEXT NOT NULL DEFAULT '',
                        `year` INTEGER,
                        `plate` TEXT NOT NULL DEFAULT '',
                        `currentOdometerKm` INTEGER NOT NULL DEFAULT 0,
                        `notes` TEXT NOT NULL DEFAULT '',
                        `createdAt` INTEGER NOT NULL
                    )
                    """.trimIndent()
                )
                database.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `car_odometer_logs` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `carId` INTEGER NOT NULL,
                        `odometerKm` INTEGER NOT NULL,
                        `date` INTEGER NOT NULL
                    )
                    """.trimIndent()
                )
                database.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `car_service_items` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `carId` INTEGER NOT NULL,
                        `name` TEXT NOT NULL,
                        `lastServiceDate` INTEGER,
                        `lastServiceOdometerKm` INTEGER,
                        `intervalKm` INTEGER,
                        `intervalDays` INTEGER,
                        `lastCost` REAL NOT NULL DEFAULT 0,
                        `reminderId` INTEGER,
                        `notes` TEXT NOT NULL DEFAULT '',
                        `createdAt` INTEGER NOT NULL
                    )
                    """.trimIndent()
                )
                database.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `car_service_logs` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `carId` INTEGER NOT NULL,
                        `serviceItemId` INTEGER,
                        `title` TEXT NOT NULL,
                        `date` INTEGER NOT NULL,
                        `odometerKm` INTEGER,
                        `cost` REAL NOT NULL DEFAULT 0,
                        `notes` TEXT NOT NULL DEFAULT '',
                        `linkedExpenseId` INTEGER
                    )
                    """.trimIndent()
                )
            }
        }
        /** Stage 2 (اتصال خودرو به سیستم مالی): one new nullable-with-default column so
         *  existing history rows are unaffected - see CarLogCategory / CarManager. */
        private val MIGRATION_9_10 = object : Migration(9, 10) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE car_service_logs ADD COLUMN category TEXT NOT NULL DEFAULT 'SERVICE'")
            }
        }
        /** Stage 3 (برنامه غذایی پایه): two new, independent tables - nothing existing
         *  touched, same additive pattern as MIGRATION_8_9. */
        private val MIGRATION_10_11 = object : Migration(10, 11) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `meal_plans` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `weekStartDate` INTEGER NOT NULL,
                        `budget` REAL NOT NULL DEFAULT 0,
                        `createdAt` INTEGER NOT NULL
                    )
                    """.trimIndent()
                )
                database.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `meal_plan_entries` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `mealPlanId` INTEGER NOT NULL,
                        `dayOfWeek` INTEGER NOT NULL,
                        `mealType` TEXT NOT NULL,
                        `recipeName` TEXT NOT NULL,
                        `estimatedCost` REAL NOT NULL
                    )
                    """.trimIndent()
                )
            }
        }
        @Volatile
        private var INSTANCE: AppDatabase? = null

        // Play-Safe test build (test-07-clean-sms): the bank_accounts / processed_sms
        // tables and their migration were removed along with the rest of SMS Banking.
        // fallbackToDestructiveMigration() below is enough to take any existing installed
        // copy of the app (schema versions 1-4, with or without those two tables) to this
        // build's version-4 schema.
        fun getDatabase(context: Context): AppDatabase {
            return INSTANCE ?: synchronized(this) {
                val instance = Room.databaseBuilder(
                    context.applicationContext,
                    AppDatabase::class.java,
                    "maliar_pro_database"
                ).addMigrations(MIGRATION_5_6, MIGRATION_6_7, MIGRATION_7_8, MIGRATION_8_9, MIGRATION_9_10, MIGRATION_10_11)
                 .fallbackToDestructiveMigration()
                 .build()
                INSTANCE = instance
                instance
            }
        }
    }
}
