package com.maliar.pro.database

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

@Database(
    entities = [Contact::class, Income::class, Expense::class, Check::class, Installment::class, Reminder::class, 
               Asset::class, Debt::class, FinancialGoal::class, FixedIncome::class, FinancialPreferences::class,
               ReminderEntity::class, Debtor::class, DebtorPayment::class,
               Car::class, CarOdometerLog::class, CarServiceItem::class, CarServiceLog::class,
               MealPlan::class, MealPlanEntry::class, UserFoodPrice::class, MarketRateHistory::class,
               MonthlyBudget::class, PeriodicPayment::class, MarketProduct::class,
               MarketPriceQuote::class, ProductPurchase::class, MarketSource::class,
               BusinessTransaction::class, ProductInventory::class, GoldTransaction::class, GoldPriceAlert::class],
    version = 25,
    exportSchema = false
)
abstract class AppDatabase : RoomDatabase() {
    
    abstract fun contactDao(): ContactDao
    abstract fun accountingDao(): AccountingDao
    abstract fun reminderDao(): ReminderDao
    abstract fun financialStatusDao(): FinancialStatusDao
    abstract fun reminderEntityDao(): ReminderEntityDao
    abstract fun debtorDao(): DebtorDao
    abstract fun carDao(): CarDao
    abstract fun mealPlanDao(): MealPlanDao
    abstract fun foodPriceDao(): FoodPriceDao
    abstract fun marketRateHistoryDao(): MarketRateHistoryDao
    abstract fun budgetDao(): BudgetDao
    abstract fun periodicPaymentDao(): PeriodicPaymentDao
    abstract fun marketAssistantDao(): MarketAssistantDao
    abstract fun businessDao(): BusinessDao
    abstract fun goldPortfolioDao(): GoldPortfolioDao
    
    companion object {
        private val MIGRATION_5_6 = object : Migration(5, 6) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE advanced_reminders ADD COLUMN soundUri TEXT NOT NULL DEFAULT 'DEFAULT_ALARM'")
            }
        }
        private val MIGRATION_6_7 = object : Migration(6, 7) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE advanced_reminders ADD COLUMN repeatIntervalDays INTEGER NOT NULL DEFAULT 0")
            }
        }
        private val MIGRATION_7_8 = object : Migration(7, 8) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE advanced_reminders ADD COLUMN linkedDebtId INTEGER")
                database.execSQL("ALTER TABLE advanced_reminders ADD COLUMN linkedDebtorId INTEGER")
                database.execSQL("ALTER TABLE advanced_reminders ADD COLUMN isAutoGenerated INTEGER NOT NULL DEFAULT 0")
            }
        }
        /** Adds the whole "خودرو" module (four new, independent tables - nothing existing
         *  is touched) plus the one new nullable column on advanced_reminders that lets its
         *  service-due reminders participate in the same duplicate-avoidance pattern as
         *  checks/installments/debts/debtors. All-additive, so existing data is untouched. */
        private val MIGRATION_8_9 = object : Migration(8, 9) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE advanced_reminders ADD COLUMN linkedCarServiceId INTEGER")
                database.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `cars` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `name` TEXT NOT NULL,
                        `brand` TEXT NOT NULL DEFAULT '',
                        `model` TEXT NOT NULL DEFAULT '',
                        `year` INTEGER,
                        `plate` TEXT NOT NULL DEFAULT '',
                        `currentOdometerKm` INTEGER NOT NULL DEFAULT 0,
                        `notes` TEXT NOT NULL DEFAULT '',
                        `createdAt` INTEGER NOT NULL
                    )
                    """.trimIndent()
                )
                database.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `car_odometer_logs` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `carId` INTEGER NOT NULL,
                        `odometerKm` INTEGER NOT NULL,
                        `date` INTEGER NOT NULL
                    )
                    """.trimIndent()
                )
                database.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `car_service_items` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `carId` INTEGER NOT NULL,
                        `name` TEXT NOT NULL,
                        `lastServiceDate` INTEGER,
                        `lastServiceOdometerKm` INTEGER,
                        `intervalKm` INTEGER,
                        `intervalDays` INTEGER,
                        `lastCost` REAL NOT NULL DEFAULT 0,
                        `reminderId` INTEGER,
                        `notes` TEXT NOT NULL DEFAULT '',
                        `createdAt` INTEGER NOT NULL
                    )
                    """.trimIndent()
                )
                database.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `car_service_logs` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `carId` INTEGER NOT NULL,
                        `serviceItemId` INTEGER,
                        `title` TEXT NOT NULL,
                        `date` INTEGER NOT NULL,
                        `odometerKm` INTEGER,
                        `cost` REAL NOT NULL DEFAULT 0,
                        `notes` TEXT NOT NULL DEFAULT '',
                        `linkedExpenseId` INTEGER
                    )
                    """.trimIndent()
                )
            }
        }
        /** Stage 2 (اتصال خودرو به سیستم مالی): one new nullable-with-default column so
         *  existing history rows are unaffected - see CarLogCategory / CarManager. */
        private val MIGRATION_9_10 = object : Migration(9, 10) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE car_service_logs ADD COLUMN category TEXT NOT NULL DEFAULT 'SERVICE'")
            }
        }
        /** Stage 3 (برنامه غذایی پایه): two new, independent tables - nothing existing
         *  touched, same additive pattern as MIGRATION_8_9. */
        private val MIGRATION_10_11 = object : Migration(10, 11) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `meal_plans` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `weekStartDate` INTEGER NOT NULL,
                        `budget` REAL NOT NULL DEFAULT 0,
                        `createdAt` INTEGER NOT NULL
                    )
                    """.trimIndent()
                )
                database.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `meal_plan_entries` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `mealPlanId` INTEGER NOT NULL,
                        `dayOfWeek` INTEGER NOT NULL,
                        `mealType` TEXT NOT NULL,
                        `recipeName` TEXT NOT NULL,
                        `estimatedCost` REAL NOT NULL
                    )
                    """.trimIndent()
                )
            }
        }
        private val MIGRATION_11_12 = object : Migration(11, 12) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE advanced_reminders ADD COLUMN repeatIntervalMinutes INTEGER NOT NULL DEFAULT 0")
            }
        }
        private val MIGRATION_12_13 = object : Migration(12, 13) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("""
                    CREATE TABLE IF NOT EXISTS `user_food_prices` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `name` TEXT NOT NULL,
                        `normalizedName` TEXT NOT NULL,
                        `pricePerUnit` REAL NOT NULL,
                        `unitLabel` TEXT NOT NULL,
                        `updatedAt` INTEGER NOT NULL
                    )
                """.trimIndent())
                database.execSQL(
                    "CREATE UNIQUE INDEX IF NOT EXISTS `index_user_food_prices_normalizedName` " +
                        "ON `user_food_prices` (`normalizedName`)"
                )
            }
        }
        /** Two independent, all-additive changes for the gold/currency-rate features:
         *  a nullable `goldGrams` column on `assets` (existing rows get NULL, so they keep
         *  behaving exactly as before - a fixed manually-entered value) and a new
         *  `market_rate_history` table (one row/day) for the reports trend chart. */
        private val MIGRATION_13_14 = object : Migration(13, 14) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE assets ADD COLUMN goldGrams REAL")
                database.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `market_rate_history` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `date` INTEGER NOT NULL,
                        `gold` REAL,
                        `currency` REAL,
                        `coinEmami` REAL,
                        `coinHalf` REAL,
                        `coinQuarter` REAL,
                        `recordedAt` INTEGER NOT NULL
                    )
                    """.trimIndent()
                )
                database.execSQL(
                    "CREATE UNIQUE INDEX IF NOT EXISTS `index_market_rate_history_date` " +
                        "ON `market_rate_history` (`date`)"
                )
            }
        }
        private val MIGRATION_14_15 = object : Migration(14, 15) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE assets ADD COLUMN purpose TEXT NOT NULL DEFAULT 'NORMAL'")
                database.execSQL("ALTER TABLE expenses ADD COLUMN accountId INTEGER")
            }
        }
        private val MIGRATION_15_16 = object : Migration(15, 16) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE assets ADD COLUMN dailyLimit REAL")
            }
        }
        private val MIGRATION_16_17 = object : Migration(16, 17) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `monthly_budgets` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `year` INTEGER NOT NULL,
                        `month` INTEGER NOT NULL,
                        `category` TEXT NOT NULL,
                        `amount` REAL NOT NULL,
                        `softThreshold` INTEGER NOT NULL DEFAULT 70,
                        `hardThreshold` INTEGER NOT NULL DEFAULT 85,
                        `isEnabled` INTEGER NOT NULL DEFAULT 1,
                        `createdAt` INTEGER NOT NULL,
                        `updatedAt` INTEGER NOT NULL
                    )
                    """.trimIndent()
                )
                database.execSQL(
                    "CREATE UNIQUE INDEX IF NOT EXISTS `index_monthly_budgets_year_month_category` " +
                        "ON `monthly_budgets` (`year`, `month`, `category`)"
                )
            }
        }
        private val MIGRATION_17_18 = object : Migration(17, 18) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `periodic_payments` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `title` TEXT NOT NULL,
                        `amount` REAL NOT NULL,
                        `accountId` INTEGER,
                        `periodDays` INTEGER NOT NULL DEFAULT 30,
                        `nextPaymentAt` INTEGER NOT NULL,
                        `category` TEXT NOT NULL DEFAULT 'عمومی',
                        `isActive` INTEGER NOT NULL DEFAULT 1,
                        `notes` TEXT NOT NULL DEFAULT '',
                        `reminderDaysBefore` INTEGER NOT NULL DEFAULT 1,
                        `lastPaidOccurrenceAt` INTEGER,
                        `createdAt` INTEGER NOT NULL,
                        `updatedAt` INTEGER NOT NULL
                    )
                    """.trimIndent()
                )
            }
        }
        private val MIGRATION_18_19 = object : Migration(18, 19) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE periodic_payments ADD COLUMN reminderId INTEGER")
            }
        }
        /** بازاریار: four isolated tables, deliberately not coupled to accounting data. */
        private val MIGRATION_19_20 = object : Migration(19, 20) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `market_products` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `name` TEXT NOT NULL, `category` TEXT NOT NULL DEFAULT '', `brand` TEXT NOT NULL DEFAULT '', `model` TEXT NOT NULL DEFAULT '', `barcode` TEXT NOT NULL DEFAULT '', `createdAt` INTEGER NOT NULL)")
                database.execSQL("CREATE TABLE IF NOT EXISTS `market_price_quotes` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `productId` INTEGER NOT NULL, `source` TEXT NOT NULL, `priceType` TEXT NOT NULL, `price` REAL NOT NULL, `minPrice` REAL, `maxPrice` REAL, `checkedAt` INTEGER NOT NULL, `confidence` REAL NOT NULL DEFAULT 0.5, `sourceUrl` TEXT NOT NULL DEFAULT '')")
                database.execSQL("CREATE INDEX IF NOT EXISTS `index_market_price_quotes_productId_checkedAt` ON `market_price_quotes` (`productId`, `checkedAt`)")
                database.execSQL("CREATE TABLE IF NOT EXISTS `product_purchases` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `productId` INTEGER NOT NULL, `purchasePrice` REAL NOT NULL, `quantity` REAL NOT NULL DEFAULT 1, `purchasedAt` INTEGER NOT NULL, `supplier` TEXT NOT NULL DEFAULT '')")
                database.execSQL("CREATE INDEX IF NOT EXISTS `index_product_purchases_productId_purchasedAt` ON `product_purchases` (`productId`, `purchasedAt`)")
                database.execSQL("CREATE TABLE IF NOT EXISTS `market_sources` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `name` TEXT NOT NULL, `url` TEXT NOT NULL, `priceType` TEXT NOT NULL, `isEnabled` INTEGER NOT NULL DEFAULT 1, `createdAt` INTEGER NOT NULL)")
            }
        }
        private val MIGRATION_20_21 = object : Migration(20, 21) {
            override fun migrate(database: SupportSQLiteDatabase) {
                // Lets an income be linked to the account it was deposited into, mirroring
                // Expense.accountId (which already existed) - the missing half needed for
                // account balances to actually track real money in/out automatically.
                database.execSQL("ALTER TABLE incomes ADD COLUMN accountId INTEGER")
            }
        }
        /** Extends the same account-linked-balance mechanism (see
         *  FinancialStatusManager.adjustAssetBalance) to installments, debts, and
         *  debtor payments, so every place money actually moves - not just plain
         *  income/expense - can keep an account's balance correct automatically. */
        private val MIGRATION_21_22 = object : Migration(21, 22) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE installments ADD COLUMN accountId INTEGER")
                database.execSQL("ALTER TABLE debts ADD COLUMN accountId INTEGER")
                database.execSQL("ALTER TABLE debtor_payments ADD COLUMN accountId INTEGER")
            }
        }
        /** «فروش کالا»: two new, nullable-with-default columns on `incomes` only - existing
         *  rows get isProductSale=0/costOfGoods=0, so every pre-existing income keeps being
         *  treated as plain service income (profit == amount) exactly as before. Nothing
         *  else (accounts, expenses, balances) is touched. See Income.kt for the fields'
         *  meaning and AccountingDao/AccountingManager for the new profit-vs-cash queries
         *  that read them. */
        private val MIGRATION_22_23 = object : Migration(22, 23) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE incomes ADD COLUMN isProductSale INTEGER NOT NULL DEFAULT 0")
                database.execSQL("ALTER TABLE incomes ADD COLUMN costOfGoods REAL NOT NULL DEFAULT 0")
            }
        }
        /** Business accounting is additive: existing incomes remain valid service/product
         * sales, while stock and non-profit cash movements get their own audit tables. */
        private val MIGRATION_23_24 = object : Migration(23, 24) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE incomes ADD COLUMN productName TEXT NOT NULL DEFAULT ''")
                database.execSQL("ALTER TABLE incomes ADD COLUMN productQuantity REAL NOT NULL DEFAULT 1")
                database.execSQL("ALTER TABLE incomes ADD COLUMN listPrice REAL NOT NULL DEFAULT 0")
                database.execSQL("ALTER TABLE incomes ADD COLUMN discountAmount REAL NOT NULL DEFAULT 0")
                database.execSQL("CREATE TABLE IF NOT EXISTS business_transactions (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, type TEXT NOT NULL, amount REAL NOT NULL, fromAccountId INTEGER, toAccountId INTEGER, date INTEGER NOT NULL, description TEXT NOT NULL DEFAULT '', supplier TEXT NOT NULL DEFAULT '', productName TEXT NOT NULL DEFAULT '', quantity REAL NOT NULL DEFAULT 0, unitCost REAL NOT NULL DEFAULT 0, createdAt INTEGER NOT NULL)")
                database.execSQL("CREATE TABLE IF NOT EXISTS product_inventory (name TEXT NOT NULL PRIMARY KEY, quantity REAL NOT NULL DEFAULT 0, averageUnitCost REAL NOT NULL DEFAULT 0, updatedAt INTEGER NOT NULL)")
            }
        }
        private val MIGRATION_24_25 = object : Migration(24, 25) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS gold_transactions (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, kind TEXT NOT NULL, type TEXT NOT NULL, quantity REAL NOT NULL, unitPrice REAL NOT NULL, fee REAL NOT NULL DEFAULT 0, date INTEGER NOT NULL, notes TEXT NOT NULL DEFAULT '', accountId INTEGER)")
                database.execSQL("CREATE TABLE IF NOT EXISTS gold_price_alerts (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, kind TEXT NOT NULL, targetPrice REAL NOT NULL, direction TEXT NOT NULL, isActive INTEGER NOT NULL DEFAULT 1, createdAt INTEGER NOT NULL)")
            }
        }
        @Volatile
        private var INSTANCE: AppDatabase? = null

        // Play-Safe test build (test-07-clean-sms): the bank_accounts / processed_sms
        // tables and their migration were removed along with the rest of SMS Banking.
        // fallbackToDestructiveMigration() below is enough to take any existing installed
        // copy of the app (schema versions 1-4, with or without those two tables) to this
        // build's version-4 schema.
        fun getDatabase(context: Context): AppDatabase {
            return INSTANCE ?: synchronized(this) {
                val instance = Room.databaseBuilder(
                    context.applicationContext,
                    AppDatabase::class.java,
                    "maliar_pro_database"
                ).addMigrations(MIGRATION_5_6, MIGRATION_6_7, MIGRATION_7_8, MIGRATION_8_9, MIGRATION_9_10, MIGRATION_10_11, MIGRATION_11_12, MIGRATION_12_13, MIGRATION_13_14, MIGRATION_14_15, MIGRATION_15_16, MIGRATION_16_17, MIGRATION_17_18, MIGRATION_18_19, MIGRATION_19_20, MIGRATION_20_21, MIGRATION_21_22, MIGRATION_22_23, MIGRATION_23_24, MIGRATION_24_25)
                 .fallbackToDestructiveMigration()
                 .build()
                INSTANCE = instance
                instance
            }
        }
    }
}
