package com.maliar.pro.database

import android.content.Context
import kotlinx.coroutines.flow.Flow

class PeriodicPaymentManager(context: Context) {
    private val appContext = context.applicationContext
    private val dao = AppDatabase.getDatabase(appContext).periodicPaymentDao()

    fun getAll(): Flow<List<PeriodicPayment>> = dao.getAll()

    suspend fun getAllList(): List<PeriodicPayment> = dao.getAllList()

    suspend fun save(payment: PeriodicPayment): Long {
        val id = dao.insert(payment)
        if (payment.isActive) ensureReminder(payment.copy(id = id))
        return id
    }

    suspend fun delete(payment: PeriodicPayment) {
        payment.reminderId?.let { id ->
            SmartReminderManager(appContext).getReminderById(id)?.let { SmartReminderManager(appContext).deleteReminder(it) }
        }
        dao.delete(payment)
    }

    suspend fun setActive(paymentId: Long, active: Boolean) {
        val current = dao.getById(paymentId) ?: return
        if (current.isActive == active) return
        if (!active) {
            current.reminderId?.let { id ->
                SmartReminderManager(appContext).getReminderById(id)?.let { SmartReminderManager(appContext).deleteReminder(it) }
            }
            dao.update(current.copy(isActive = false, reminderId = null, updatedAt = System.currentTimeMillis()))
        } else {
            ensureReminder(current.copy(isActive = true, reminderId = null, updatedAt = System.currentTimeMillis()))
        }
    }

    suspend fun markPaid(paymentId: Long): PeriodicPayment? {
        val current = dao.getById(paymentId) ?: return null
        if (!current.isActive || current.lastPaidOccurrenceAt == current.nextPaymentAt) return null
        val updated = current.copy(
            lastPaidOccurrenceAt = current.nextPaymentAt,
            nextPaymentAt = current.nextPaymentAt + current.periodDays.coerceAtLeast(1) * DAY_MILLIS,
            updatedAt = System.currentTimeMillis()
        )
        dao.update(updated)
        AccountingManager(appContext).addExpense(
            Expense(
                amount = current.amount,
                description = "پرداخت دوره‌ای: ${current.title}",
                date = current.nextPaymentAt,
                category = current.category,
                accountId = current.accountId
            )
        )
        return current
    }

    private suspend fun ensureReminder(payment: PeriodicPayment) {
        val manager = SmartReminderManager(appContext)
        val trigger = payment.nextPaymentAt - payment.reminderDaysBefore.coerceIn(0, 30) * DAY_MILLIS
        val reminderId = manager.addReminder(
            ReminderEntity(
                title = "پرداخت دوره‌ای: ${payment.title}",
                description = "مبلغ ${String.format(java.util.Locale.US, "%,.0f", payment.amount)} تومان",
                reminderType = ReminderType.BILL_PAYMENT.name,
                priority = Priority.HIGH.name,
                alertType = AlertType.NOTIFICATION.name,
                triggerTime = trigger,
                repeatPattern = RepeatPattern.CUSTOM.name,
                repeatIntervalDays = payment.periodDays.coerceAtLeast(1),
                category = payment.category,
                isAutoGenerated = true,
                soundUri = "RAW:reminder_voice_39"
            )
        )
        dao.update(payment.copy(reminderId = reminderId, updatedAt = System.currentTimeMillis()))
    }

    companion object {
        private const val DAY_MILLIS = 24L * 60 * 60 * 1000

        @JvmStatic
        fun detectPeriodDays(title: String, description: String = ""): Int? {
            val text = "$title $description".trim().lowercase(java.util.Locale.ROOT)
                .replace('ي', 'ی').replace('ى', 'ی').replace('ك', 'ک')
                .filter { it.isLetterOrDigit() || it == ' ' }

            val words = text.split(" ").filter { it.isNotBlank() }
            val containsRent = words.any { w -> w.contains("اجاره") }

            // اول الگوهای صریح سالانه (قبل از ماهانه چون "ماه" در "سال" نیست)
            if (text.contains("سالانه") || text.contains("سالیانه") ||
                text.contains("اجاره سال") || text.contains("اجاره سالانه") ||
                text.contains("اجاره هر سال") || text.contains("yearly") ||
                (text.contains("هر سال") && containsRent)) return 365

            // الگوهای هفتگی
            if (text.contains("هفتگی") || text.contains("سر هفته") ||
                text.contains("اجاره هفته") || text.contains("اجاره هفتگی") ||
                text.contains("اجاره سر هفته") || text.contains("اجاره هر هفته") ||
                text.contains("weekly") ||
                (text.contains("هر هفته") && containsRent) ||
                (words.any { it == "هفته" } && containsRent)) return 7

            // الگوهای ماهانه (فقط با کلمه کلیدی مشخص، نه صرفاً "ماه")
            if (text.contains("ماهانه") || text.contains("ماهیانه") ||
                text.contains("سر ماه") ||
                text.contains("اجاره ماه") || text.contains("اجاره ماهانه") ||
                text.contains("اجاره سر ماه") || text.contains("اجاره هر ماه") ||
                text.contains("اجاره منزل") || text.contains("اجاره خانه") ||
                text.contains("اجاره نامه") ||
                text.contains("regular monthly") || text.contains("monthly") ||
                (words.any { it == "ماهی" } && containsRent)) return 30

            // اگر "اجاره" دارد ولی دوره مشخص نشده، پیش‌فرض ماهانه
            if (containsRent) return 30

            return null
        }
    }
}
