package com.maliar.pro.database

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "advanced_reminders")
data class ReminderEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val title: String,
    val description: String = "",
    val reminderType: String = ReminderType.SIMPLE.name,
    val priority: String = Priority.MEDIUM.name,
    val alertType: String = AlertType.NOTIFICATION.name,
    val triggerTime: Long,
    val repeatPattern: String = RepeatPattern.ONCE.name,
    /** Used when repeatPattern is CUSTOM: run again after this many calendar days. */
    val repeatIntervalDays: Int = 0,
    val repeatIntervalMinutes: Int = 0,
    val customRepeatDays: String = "", // comma-separated: "0,1,2,3,4,5,6"
    val locationLat: Double? = null,
    val locationLng: Double? = null,
    val locationRadius: Int = 100,
    val locationName: String = "",
    val isCompleted: Boolean = false,
    val completedAt: Long? = null,
    val createdAt: Long = System.currentTimeMillis(),
    val tags: String = "",
    val relatedPerson: String = "",
    val snoozeCount: Int = 0,
    val lastSnoozed: Long? = null,
    val notes: String = "",
    val category: String = "",
    val linkedCheckId: Long? = null,
    val linkedInstallmentId: Long? = null,
    /** Same idea as the two fields above, for the newer Debt (loans, in FinancialStatus)
     *  and Debtor (person owes/owed) records - lets DueDateReminderWorker check "does this
     *  due item already have a reminder?" without creating duplicates every day. */
    val linkedDebtId: Long? = null,
    val linkedDebtorId: Long? = null,
    /** Same idea, for CarServiceItem (بخش خودرو) - lets DueDateReminderWorker check "does
     *  this service item already have an open reminder?" the same way it does for checks/
     *  installments/debts/debtors. */
    val linkedCarServiceId: Long? = null,
    /** True only for reminders DueDateReminderWorker created automatically (never set by
     *  the person themselves) - shown with a small badge in the list and safe to silently
     *  clean up if its source check/installment/debt/debtor no longer exists or is settled. */
    val isAutoGenerated: Boolean = false,
    // Optional contact attached to this reminder so an "action" notification can offer a
    // real "call" button (dials the exact person picked from the app's own Contacts tab,
    // instead of only "done"/"snooze").
    val contactName: String = "",
    val contactPhoneNumber: String = "",
    /** Per-reminder sound: DEFAULT_ALARM, RAW:<resource name>, or a persisted content URI. */
    val soundUri: String = "DEFAULT_ALARM"
)

enum class ReminderType {
    SIMPLE, RECURRING, LOCATION_BASED, BIRTHDAY, ANNIVERSARY, BILL_PAYMENT, MEDICINE, TASK, CONDITIONAL
}

enum class AlertType {
    NONE, NOTIFICATION, FULL_SCREEN, SMART
}

enum class RepeatPattern {
    ONCE, DAILY, WEEKLY, MONTHLY, YEARLY, WEEKDAYS, WEEKENDS, CUSTOM, CUSTOM_INTERVAL
}
