package com.maliar.pro.utils

import android.content.Context
import android.util.Log
import androidx.work.CoroutineWorker
import androidx.work.ExistingPeriodicWorkPolicy
import androidx.work.PeriodicWorkRequestBuilder
import androidx.work.WorkManager
import androidx.work.WorkerParameters
import com.maliar.pro.database.AccountingManager
import com.maliar.pro.database.AlertType
import com.maliar.pro.database.CarManager
import com.maliar.pro.database.DebtorDirection
import com.maliar.pro.database.DebtorManager
import com.maliar.pro.database.FinancialStatusManager
import com.maliar.pro.database.Priority
import com.maliar.pro.database.ReminderEntity
import com.maliar.pro.database.ReminderType
import com.maliar.pro.database.RepeatPattern
import com.maliar.pro.database.SmartReminderManager
import kotlinx.coroutines.flow.first
import java.util.concurrent.TimeUnit

/**
 * Runs once a day (while "یادآوری خودکار سررسیدها" is on) and makes sure every check,
 * installment, unpaid debt, and person debtor/creditor whose due date falls within the
 * next [PreferencesManager.getAutoDueReminderDaysBefore] days has at least one reminder -
 * without ever creating a duplicate for something the person already set a reminder for
 * themselves (checked via the linkedCheckId/linkedInstallmentId/linkedDebtId/linkedDebtorId
 * fields on every existing reminder, not just the auto-generated ones).
 */
class DueDateReminderWorker(context: Context, params: WorkerParameters) : CoroutineWorker(context, params) {

    override suspend fun doWork(): Result {
        val prefs = PreferencesManager(applicationContext)
        if (!prefs.isAutoDueRemindersEnabled()) return Result.success()

        return try {
            val daysBefore = prefs.getAutoDueReminderDaysBefore()
            val windowEnd = System.currentTimeMillis() + daysBefore.toLong() * 24 * 60 * 60 * 1000

            val accountingManager = AccountingManager(applicationContext)
            val financialStatusManager = FinancialStatusManager(applicationContext)
            val debtorManager = DebtorManager(applicationContext)
            val smartReminderManager = SmartReminderManager(applicationContext)

            val existingReminders = com.maliar.pro.database.AppDatabase.getDatabase(applicationContext)
                .reminderEntityDao().getAllRemindersList()
            val existingCheckIds = existingReminders.mapNotNull { it.linkedCheckId }.toSet()
            val existingInstallmentIds = existingReminders.mapNotNull { it.linkedInstallmentId }.toSet()
            val existingDebtIds = existingReminders.mapNotNull { it.linkedDebtId }.toSet()
            val existingDebtorIds = existingReminders.mapNotNull { it.linkedDebtorId }.toSet()

            // Checks
            accountingManager.getAllChecksList()
                .filter { !it.isCashed && it.dueDate <= windowEnd && it.id !in existingCheckIds }
                .forEach { check ->
                    smartReminderManager.addReminder(
                        ReminderEntity(
                            title = "سررسید چک ${check.checkNumber}".trim(),
                            description = check.recipient.ifBlank { check.issuer },
                            reminderType = ReminderType.BILL_PAYMENT.name,
                            priority = Priority.HIGH.name,
                            alertType = AlertType.FULL_SCREEN.name,
                            triggerTime = reminderTimeFor(check.dueDate),
                            repeatPattern = RepeatPattern.ONCE.name,
                            linkedCheckId = check.id,
                            soundUri = "RAW:reminder_voice_23", // یادآوری شما فرا رسیده است
                            isAutoGenerated = true
                        )
                    )
                }

            // Installments
            accountingManager.getAllInstallmentsList().forEach { installment ->
                if (installment.id in existingInstallmentIds) return@forEach
                val due = FinanceCalendarUtils.nextInstallmentDueDate(installment) ?: return@forEach
                if (due > windowEnd) return@forEach
                smartReminderManager.addReminder(
                    ReminderEntity(
                        title = "سررسید قسط: ${installment.title}",
                        description = "قسط ${installment.paidInstallments + 1} از ${installment.totalInstallments}",
                        reminderType = ReminderType.BILL_PAYMENT.name,
                        priority = Priority.HIGH.name,
                        alertType = AlertType.FULL_SCREEN.name,
                        triggerTime = reminderTimeFor(due),
                        repeatPattern = RepeatPattern.ONCE.name,
                        linkedInstallmentId = installment.id,
                        soundUri = "RAW:reminder_voice_18", // قسط شما امروز سررسید می شود
                        isAutoGenerated = true
                    )
                )
            }

            // Debts (loans, from Financial Status tab)
            financialStatusManager.getAllDebtsList()
                .filter { !it.isPaid && it.endDate != null && it.endDate <= windowEnd && it.id !in existingDebtIds }
                .forEach { debt ->
                    smartReminderManager.addReminder(
                        ReminderEntity(
                            title = "سررسید بدهی: ${debt.title}",
                            description = "بدهی",
                            reminderType = ReminderType.BILL_PAYMENT.name,
                            priority = Priority.HIGH.name,
                            alertType = AlertType.FULL_SCREEN.name,
                            triggerTime = reminderTimeFor(debt.endDate!!),
                            repeatPattern = RepeatPattern.ONCE.name,
                            linkedDebtId = debt.id,
                            soundUri = "RAW:reminder_voice_31", // یک پرداخت عقب افتاده دارید
                            isAutoGenerated = true
                        )
                    )
                }

            // Debtors / creditors (people)
            debtorManager.getAllDebtors().first()
                .filter { !it.isSettled && it.dueDate != null && it.dueDate <= windowEnd && it.id !in existingDebtorIds }
                .forEach { debtor ->
                    val theyOweMe = debtor.direction == DebtorDirection.THEY_OWE_ME
                    smartReminderManager.addReminder(
                        ReminderEntity(
                            title = if (theyOweMe) "پیگیری طلب از ${debtor.name}" else "پرداخت بدهی به ${debtor.name}",
                            description = if (theyOweMe) "بدهکار به شما" else "شما بدهکارید",
                            reminderType = ReminderType.BILL_PAYMENT.name,
                            priority = Priority.HIGH.name,
                            alertType = AlertType.FULL_SCREEN.name,
                            triggerTime = reminderTimeFor(debtor.dueDate!!),
                            repeatPattern = RepeatPattern.ONCE.name,
                            linkedDebtorId = debtor.id,
                            contactName = if (debtor.phoneNumber.isNotBlank()) debtor.name else "",
                            contactPhoneNumber = debtor.phoneNumber,
                            soundUri = if (theyOweMe) "RAW:reminder_voice_10" else "RAW:reminder_voice_29",
                            isAutoGenerated = true
                        )
                    )
                }

            // Cars: service items overdue or coming up soon (by km, by date, or whichever
            // of the two - see CarServiceStatusCalculator) get exactly one open reminder
            // each, the same duplicate-avoidance pattern as everything else in this worker.
            val carManager = CarManager(applicationContext)
            val existingCarServiceIds = existingReminders.mapNotNull { it.linkedCarServiceId }.toSet()
            carManager.getAllCarsList().forEach { car ->
                carManager.getServiceItemsList(car.id)
                    .filter { it.id !in existingCarServiceIds }
                    .forEach { item ->
                        val status = CarServiceStatusCalculator.compute(
                            item, car.currentOdometerKm, soonDaysThreshold = daysBefore.toLong()
                        )
                        if (status.urgency != CarServiceUrgency.OVERDUE && status.urgency != CarServiceUrgency.SOON) {
                            return@forEach
                        }
                        val overdue = status.urgency == CarServiceUrgency.OVERDUE
                        val triggerTime = item.nextDueDate?.let { reminderTimeFor(it) }
                            ?: (System.currentTimeMillis() + 60_000)
                        val reminderId = smartReminderManager.addReminder(
                            ReminderEntity(
                                title = if (overdue) "🔴 سرویس ${item.name} (${car.name}) از موعد گذشته"
                                        else "🔔 سرویس ${item.name} (${car.name}) نزدیک است",
                                description = car.name,
                                reminderType = ReminderType.BILL_PAYMENT.name,
                                priority = if (overdue) Priority.HIGH.name else Priority.MEDIUM.name,
                                alertType = AlertType.NOTIFICATION.name,
                                triggerTime = triggerTime,
                                repeatPattern = RepeatPattern.ONCE.name,
                                linkedCarServiceId = item.id,
                                isAutoGenerated = true
                            )
                        )
                        carManager.updateServiceItem(item.copy(reminderId = reminderId))
                    }
            }

            Result.success()
        } catch (e: Exception) {
            Log.e(TAG, "Failed to auto-generate due-date reminders", e)
            Result.success() // best-effort feature; never worth retrying/crashing over
        }
    }

    /** Reminders fire at 9 AM on the due date itself (or right now, if the due date has
     *  already technically passed by the time this worker runs) rather than at the exact
     *  due-date timestamp (which is usually just midnight and not a moment the person is
     *  actually looking at their phone). */
    private fun reminderTimeFor(dueDate: Long): Long {
        val cal = java.util.Calendar.getInstance()
        cal.timeInMillis = dueDate
        cal.set(java.util.Calendar.HOUR_OF_DAY, 9)
        cal.set(java.util.Calendar.MINUTE, 0)
        cal.set(java.util.Calendar.SECOND, 0)
        val candidate = cal.timeInMillis
        return if (candidate < System.currentTimeMillis()) System.currentTimeMillis() + 60_000 else candidate
    }

    companion object {
        private const val TAG = "DueDateReminderWorker"
        private const val UNIQUE_WORK_NAME = "maliar_pro_due_date_reminders"

        fun schedule(context: Context) {
            val request = PeriodicWorkRequestBuilder<DueDateReminderWorker>(1, TimeUnit.DAYS).build()
            WorkManager.getInstance(context).enqueueUniquePeriodicWork(
                UNIQUE_WORK_NAME,
                ExistingPeriodicWorkPolicy.KEEP,
                request
            )
        }

        fun cancel(context: Context) {
            WorkManager.getInstance(context).cancelUniqueWork(UNIQUE_WORK_NAME)
        }
    }
}
